// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/service/internal/dao/internal"
)

// desktopDao is the data access object for table desktop.
// You can define custom methods on it to extend its functionality as you wish.
type desktopDao struct {
	*internal.DesktopDao
}

var (
	// Desktop is globally public accessible object for table desktop operations.
	Desktop = desktopDao{
		internal.NewDesktopDao(),
	}
)

// Fill with you ideas below.
