// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-30 16:22:20
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Desktop is the golang structure for table desktop.
type Desktop struct {
	Uuid            string      `json:"uuid"            description:"桌面uuid"`
	VmUuid          string      `json:"vmUuid"          description:"虚拟化平台上虚机的uuid"`
	DisplayName     string      `json:"displayName"     description:"桌面的显示名称"`
	GpuAttachStatus string      `json:"gpuAttachStatus" description:"桌面挂载gpu状态，'pre_attached'表示预挂载，即关联了GPU规格的关机态虚机,'attached'表示已经挂载,'unattached'表示未挂载"`
	Enabled         string      `json:"enabled"         description:"桌面的启用状态，enabled表示启用，disabled表示桌面已禁用"`
	NodeUuid        string      `json:"nodeUuid"        description:"物理机uuid"`
	NodeName        string      `json:"nodeName"        description:"物理机名称"`
	IsDefault       int         `json:"isDefault"       description:"是否是默认桌面，False表示不是，True表示是。默认False。"`
	Desc            string      `json:"desc"            description:"桌面的描述信息"`
	CreatedAt       *gtime.Time `json:"createdAt"       description:"创建时间"`
	UpdatedAt       *gtime.Time `json:"updatedAt"       description:"最后修改时间"`
}
