// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-04-06 16:59:07
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Uuid        string      `json:"uuid"        description:"uuid"`
	LoginName   string      `json:"loginName"   description:"登录名"`
	DisplayName string      `json:"displayName" description:"姓名"`
	Password    string      `json:"password"    description:"密码"`
	Email       string      `json:"email"       description:"邮箱"`
	Phone       string      `json:"phone"       description:"电话"`
	Enabled     string      `json:"enabled"     description:"用户的启用状态，1表示enabled：启用，0表示disabled：禁用"`
	Desc        string      `json:"desc"        description:"描述信息"`
	CreatedAt   *gtime.Time `json:"createdAt"   description:"创建时间"`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:"最后修改时间"`
}
